//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Currency_Exchange_Rates_Calculator
{
    using System;
    using System.Collections.Generic;
    
    public partial class Currency
    {
        public string CurrencyName { get; set; }
        public double CurrencyRate { get; set; }
    }
}
